/*
href="https://projecteuler.net/problem=2"
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
#include <bits/stdc++.h>
using namespace std;
typedef long long ll;
int main()
{
    //1000000
    ll sum=0;
    vector<ll>fib;
    fib.push_back(1);
    fib.push_back(2);
    sum=2;
    for(int i=1;fib[i]<4000000;i++){
        fib.push_back(fib[i]+fib[i-1]);
        if(fib[i+1]%2==0)
            sum+=fib[i+1];
    }
    cout<<sum;
}
